apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dm
  labels:
    app: jenkins
spec:
  replicas: 8
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins
        ports:
        - containerPort: 8080