apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nop-deploy
  labels:
    app: nop  
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: nop
  template:
    metadata:
      name: nop
    spec:
      containers: 
        - name: nop-cont  
          image: archanaraj/nop:latest
          ports :
            - ContainerPort: 5000    
