---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_PASSWORD: MTIzNDUK #12345
  MYSQL_ROOT_PASSWORD: bXlwYXNzd29yZAo= #mypassword
  MYSQL_DATABASE: ZW1wbG95ZWVzCg== #employees
  MYSQL_USER: YXJjaGFuYQ== #archana