---
apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  template:
    metadata:
      name: jobpod
    spec:
      containers:
        - image: alpine
          command:
            - sleep
            - 10s


# kubectl apply -f hellojob.yml
# kubectl get jobs -w
# kubectl get po
# kubectl delete jobs.batch hellojob
# kubectl get jobs
# kubectl get po           