---
apiVersion: batch/v1
kind: Job
metadata:
  name: hellojob
spec:
  backoffLimit: 2
  template:
    metadata:
      name: jobpod
    spec:
      restartPolicy: OnFailure
      containers:
        - name: alpine  
          image: alpine
          command:
            - sleep
            - 10s


# kubectl apply -f hellojob.yml
# kubectl get jobs -w
# kubectl get po
# kubectl delete jobs.batch hellojob
# kubectl get jobs
# kubectl get po           