---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: periodicjob
spec:
  schedule: '* * * * *' 
  jobTemplate:
    metadata:
      name: getlivedata
    spec:
      template:
        metadata:
          name: livedatapod
        spec:
          containers:
            - name: alpine
              image: alpine
              command:
                - sleep
                - 3s


# kubectl apply -f runmultipletimes.yml
# kubectl get cronjobs.batch
# kubectl get cronjobs.batch -w
# kubectl get jobs.batch
# kubectl get po
# kubectl delete cronjobs.batch runmultipletimes.yml
# kubectl get cronjobs.batch
# kubectl get jobs.batch
# kubectl get po              