---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nop-dp
  labels:
    app: nop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nop
  template: 
    metadata:
      name: nop
      labels:
        app: nop
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      containers:
      - name: nopcont
        image: archanaraj/nop:latest
        ports:
        - containerPort: 5000     
---
apiVersion: v1
kind: Service
metadata: 
  name: nop-lb
spec:
  selector:
    app: nop
  ports:
    - name: nop 
      port: 32000
      targetPort: 5000 
  type: LoadBalancer         
