apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nop
spec:
  containers:
    - name: nopcont
      image: archanaraj/nop:latest
      ports:
        - containerPort: 5000
      replicas: 1
      selector:
        matchLabels:
          name: nop
      template: 
        metadata:
          name: nop
        spec:
          containers:
            - name: nop
            - containerPort: 5000        
        livenessProbe:
          httpGet:
            path: /

