---
apiVersion: v1
kind: Pod
metadata:
  name: restartnever
spec:
  restartPolicy: Always
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 3s


# kubectl apply -f restartalways.yml
# kubectl get pods -w        

