headless service file for mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306 
  clusterIP: "None"
  selector:
    app: mysql    
  
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
spec: 
  clusterIP: "None"
  ports:
    - port: 3306